### ISSUE TITLE
Unused argument incorrectly passed in Dolomite wrapper

### ISSUE THREAD

**Issue by devtooligan** [alcueca/erc7399-wrappers#45]
**This does not appear to present any security risk currently.**

https://github.com/alcueca/erc7399-wrappers/blob/d55c154fe447745d43d3437b46d1df2c181fc762/src/dolomite/DolomiteWrapper.sol#L74

https://github.com/alcueca/erc7399-wrappers/blob/d55c154fe447745d43d3437b46d1df2c181fc762/src/dolomite/DolomiteWrapper.sol#L84

For the `Withdraw` and `Deposit` actions created in the Dolomite wrapper, the `otherAddress` member of the `ActionArgs` struct is set and passed as an argument to `Dolomite.operate()`.  

However, according to the [documentation](https://github.com/alcueca/erc7399-wrappers/blob/main/src/dolomite/DolomiteWrapper.sol#L74), this field is not used for `Withdraw` and `Deposit` and therefore may be removed.  

Also note, in this same contract this `otherAddress` field is **correctly** being used for `Call` along with the `data` field.

**Comment by alcueca** [comment]
The link to the documentation is wrong, but I assume that it intended to point [here](https://docs.dolomite.io/developer-documentation/dolomite-margin-glossary#operations). In there, it specifies that `otherAddress` is unused, and same for `primaryMarketId`.

However, [here](https://docs.dolomite.io/developer-documentation/dolomite-margin-glossary#withdraw) the `Withdraw` action takes a `to` parameter. I assume that the first linked documentation is wrong, and the `otherAddress` parameter in `Action` is actually used as `to` in `Withdraw`. Otherwise that feature would be not implemented, which would be weird.

Furthermore, our tests use a [separate contract](https://github.com/alcueca/erc7399-wrappers/blob/d55c154fe447745d43d3437b46d1df2c181fc762/test/MockBorrower.sol#L22) to receive the flash loans, which the MockBorrower [pulls funds from](https://github.com/alcueca/erc7399-wrappers/blob/d55c154fe447745d43d3437b46d1df2c181fc762/test/MockBorrower.sol#L58). Given that we are giving the `loanReceiver` address to Dolomite in the `otherAddress` variable, and the funds are actually appearing in the `loanReceiver` (shown below) it follows that the implementation is right, and the documentation wrong.

<img width="1049" alt="image" src="https://github.com/alcueca/erc7399-wrappers/assets/38806121/9bc1b76c-93f1-4db1-8faf-30412288a785">

On `primaryMarketId` being also described as "unused" in the same documentation, Dolomite uses a single contract as entry point for all operations and the only way that we can tell Dolomite which token we are taking a flash loan of is with `primaryMarketId` as seen [here](https://github.com/alcueca/erc7399-wrappers/blob/d55c154fe447745d43d3437b46d1df2c181fc762/src/dolomite/DolomiteWrapper.sol#L68). As a test, if we don't pass a `primaryMarketId` to `Withdraw` the token transferred from Dolomite to LoanReceiver is not the `asset` that we wanted to borrow (probably it defaults to something).

From Dolomite to LoanReceiver:
<img width="1021" alt="image" src="https://github.com/alcueca/erc7399-wrappers/assets/38806121/d65ca6ce-fc30-4f7a-a364-d6fb950acfba">

Attempted retrieval of `asset`
<img width="1018" alt="image" src="https://github.com/alcueca/erc7399-wrappers/assets/38806121/10723b6a-2afc-4a4e-8593-d36cbc186a12">

**Comment by ultrasecreth** [comment]
Sorry, but where does it say `primaryMarketId` is unused? 
<img width="666" alt="image" src="https://github.com/alcueca/erc7399-wrappers/assets/241804/5c50dc63-cd3c-440a-83c5-56a8d501e76c">
First comment says it's needed for `Deposit` & `Withdraw`

**Comment by devtooligan** [comment]
Great, I'm glad this wasn't an issue after all.

I think it says not needed for otherAddress and data.  Agree with ultrasecreth it says it's needed for primaryMArketId.

Anyways, closing, sorry for the fire drill!
